"""user reminders table

Revision ID: 2444a0541f69
Revises: 91fe222cdbfd
Create Date: 2025-01-11 19:20:43.183138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2444a0541f69'
down_revision = '91fe222cdbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('launch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'launch_id')
    )
    with op.batch_alter_table('user_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reminders_launch_id'), ['launch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reminders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_reminders_launch_id'))

    op.drop_table('user_reminders')
    # ### end Alembic commands ###
