"""empty message

Revision ID: 5dc955ebd659
Revises: 7c6511ea4f82
Create Date: 2024-11-20 20:45:32.996948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc955ebd659'
down_revision = '7c6511ea4f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('launch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('launch_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_launch_reminders_launch_id'), ['launch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_launch_reminders_launch_id'))

    op.drop_table('launch_reminders')
    # ### end Alembic commands ###
