"""Drop LaunchEvent table

Revision ID: 7c6511ea4f82
Revises: 3fd176bb8f95
Create Date: 2024-11-18 22:34:03.010073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c6511ea4f82'
down_revision = '3fd176bb8f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launch_events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_events',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('launch_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('category', mysql.ENUM('NEW_LAUNCH', 'LAUNCH_UPDATE', 'LAUNCH_DELETE', 'REMINDER'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.id'], name='launch_events_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('launch_events', schema=None) as batch_op:
        batch_op.create_index('ix_launch_events_name', ['name'], unique=False)
        batch_op.create_index('ix_launch_events_launch_id', ['launch_id'], unique=False)

    # ### end Alembic commands ###
