"""rockets launchsites rocketlaunches tables

Revision ID: 99ad6bb9e58a
Revises: 3bb6ccefd8e2
Create Date: 2024-06-13 00:46:02.288384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ad6bb9e58a'
down_revision = '3bb6ccefd8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('launch_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_launch_sites_name'), ['name'], unique=True)

    op.create_table('rockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=False),
    sa.Column('payload_capacity', sa.Float(), nullable=False),
    sa.Column('thrust_at_liftoff', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rockets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rockets_name'), ['name'], unique=True)

    op.create_table('rocket_launches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('launch_timestamp', sa.DateTime(), nullable=False),
    sa.Column('rocket_id', sa.Integer(), nullable=False),
    sa.Column('launch_site_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['launch_site_id'], ['launch_sites.id'], ),
    sa.ForeignKeyConstraint(['rocket_id'], ['rockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rocket_launches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rocket_launches_launch_site_id'), ['launch_site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rocket_launches_mission'), ['mission'], unique=False)
        batch_op.create_index(batch_op.f('ix_rocket_launches_rocket_id'), ['rocket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rocket_launches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rocket_launches_rocket_id'))
        batch_op.drop_index(batch_op.f('ix_rocket_launches_mission'))
        batch_op.drop_index(batch_op.f('ix_rocket_launches_launch_site_id'))

    op.drop_table('rocket_launches')
    with op.batch_alter_table('rockets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rockets_name'))

    op.drop_table('rockets')
    with op.batch_alter_table('launch_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_launch_sites_name'))

    op.drop_table('launch_sites')
    # ### end Alembic commands ###
