"""launch reminders unique launch

Revision ID: 9b842dbb7ee5
Revises: 2444a0541f69
Create Date: 2025-01-13 14:43:39.971906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b842dbb7ee5'
down_revision = '2444a0541f69'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DELETE FROM launch_reminders duplicate USING launch_reminders original "
               "WHERE duplicate.launch_id = original.launch_id AND duplicate.id > original.id")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_launch_reminders_launch_id')
        batch_op.create_index(batch_op.f('ix_launch_reminders_launch_id'), ['launch_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_launch_reminders_launch_id'))
        batch_op.create_index('ix_launch_reminders_launch_id', ['launch_id'], unique=False)

    # ### end Alembic commands ###
