"""spaceship createdby

Revision ID: e98545d72c71
Revises: 2fe27117bc02
Create Date: 2024-06-14 01:00:48.831924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e98545d72c71'
down_revision = '2fe27117bc02'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint('rocket_launches_ibfk_1', 'rocket_launches', type_='foreignkey')
    op.drop_constraint('rocket_launches_ibfk_2', 'rocket_launches', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaceships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=False),
    sa.Column('payload_capacity', sa.Float(), nullable=False),
    sa.Column('thrust_at_liftoff', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaceships_name'), ['name'], unique=True)

    op.create_table('launches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('launch_timestamp', sa.DateTime(), nullable=False),
    sa.Column('spaceship_id', sa.Integer(), nullable=False),
    sa.Column('launch_site_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['launch_site_id'], ['launch_sites.id'], ),
    sa.ForeignKeyConstraint(['spaceship_id'], ['spaceships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('launches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_launches_launch_site_id'), ['launch_site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_launches_mission'), ['mission'], unique=False)
        batch_op.create_index(batch_op.f('ix_launches_spaceship_id'), ['spaceship_id'], unique=False)

    op.drop_table('rockets')
    with op.batch_alter_table('rocket_launches', schema=None) as batch_op:
        batch_op.drop_index('ix_rocket_launches_launch_site_id')
        batch_op.drop_index('ix_rocket_launches_mission')
        batch_op.drop_index('ix_rocket_launches_rocket_id')

    op.drop_table('rocket_launches')
    with op.batch_alter_table('launch_sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', server_default='spectator')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_sites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    op.create_table('rocket_launches',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('mission', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('launch_timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('rocket_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('launch_site_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['launch_site_id'], ['launch_sites.id'], name='rocket_launches_ibfk_1'),
    sa.ForeignKeyConstraint(['rocket_id'], ['rockets.id'], name='rocket_launches_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rocket_launches', schema=None) as batch_op:
        batch_op.create_index('ix_rocket_launches_rocket_id', ['rocket_id'], unique=False)
        batch_op.create_index('ix_rocket_launches_mission', ['mission'], unique=False)
        batch_op.create_index('ix_rocket_launches_launch_site_id', ['launch_site_id'], unique=False)

    op.create_table('rockets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('height', mysql.FLOAT(), nullable=False),
    sa.Column('mass', mysql.FLOAT(), nullable=False),
    sa.Column('payload_capacity', mysql.FLOAT(), nullable=False),
    sa.Column('thrust_at_liftoff', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('launches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_launches_spaceship_id'))
        batch_op.drop_index(batch_op.f('ix_launches_mission'))
        batch_op.drop_index(batch_op.f('ix_launches_launch_site_id'))

    op.drop_table('launches')
    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaceships_name'))

    op.drop_table('spaceships')
    # ### end Alembic commands ###
